workflows:
  cordova-android:
    name: Cordova Android App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 11
      xcode: 16.2
      vars:
        CORDOVA_VERSION: 12.0.0
        NODE_VERSION: 18.17.1
    scripts:
      - name: Установка Node.js
        script: |
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node --version
          npm --version
      - name: Проверка среды разработки
        script: |
          echo "Текущая директория: $(pwd)"
          ls -la
      - name: Установка зависимостей проекта
        script: |
          npm cache clean --force
          npm install
      - name: Сборка Vue.js проекта
        script: |
          npm run build
          # Убедимся, что директория dist существует
          if [ ! -d "dist" ]; then
            echo "Ошибка: директория dist не найдена после сборки"
            exit 1
          fi
      - name: Установка Cordova
        script: |
          npm install -g cordova@$CORDOVA_VERSION
          cordova -v
      - name: Создание Cordova проекта
        script: |
          # Создаем временную директорию для Cordova проекта
          mkdir -p cordova_project
          cd cordova_project
          
          # Инициализируем Cordova проект
          cordova create . com.example.app AppName
          
          # Копируем собранное Vue приложение в www директорию Cordova
          rm -rf www/*
          cp -r ../dist/* www/
          
          # Проверяем, что файлы скопированы успешно
          ls -la www/
      - name: Добавление Android платформы
        script: |
          cd cordova_project
          cordova platform add android
      - name: Сборка APK (debug)
        script: |
          cd cordova_project
          cordova build android --debug --verbose
    artifacts:
      - cordova_project/platforms/android/app/build/outputs/apk/debug/*.apk
